declare namespace react {
    class Component {
        constructor(props: any, context: any, updater: any);
        forceUpdate(callback: any): void;
        setState(partialState: any, callback: any): void;
    }
    class PureComponent {
        constructor(props: any, context: any, updater: any);
        forceUpdate(callback: any): void;
        setState(partialState: any, callback: any): void;
    }
    const version: string;
    function cloneElement(element: any, props: any, children: any, ...args: any[]): any;
    function createClass(spec: any): any;
    function createElement(type: any, props: any, children: any, ...args: any[]): any;
    function createFactory(type: any): any;
    function createMixin(mixin: any): any;
    function isValidElement(object: any): any;
    namespace Children {
        function count(children: any, context: any): any;
        function forEach(children: any, forEachFunc: any, forEachContext: any): any;
        function map(children: any, func: any, context: any): any;
        function only(children: any): any;
        function toArray(children: any): any;
    }
    namespace DOM {
        function a(p0: any, p1: any): any;
        function abbr(p0: any, p1: any): any;
        function address(p0: any, p1: any): any;
        function area(p0: any, p1: any): any;
        function article(p0: any, p1: any): any;
        function aside(p0: any, p1: any): any;
        function audio(p0: any, p1: any): any;
        function b(p0: any, p1: any): any;
        function base(p0: any, p1: any): any;
        function bdi(p0: any, p1: any): any;
        function bdo(p0: any, p1: any): any;
        function big(p0: any, p1: any): any;
        function blockquote(p0: any, p1: any): any;
        function body(p0: any, p1: any): any;
        function br(p0: any, p1: any): any;
        function button(p0: any, p1: any): any;
        function canvas(p0: any, p1: any): any;
        function caption(p0: any, p1: any): any;
        function circle(p0: any, p1: any): any;
        function cite(p0: any, p1: any): any;
        function clipPath(p0: any, p1: any): any;
        function code(p0: any, p1: any): any;
        function col(p0: any, p1: any): any;
        function colgroup(p0: any, p1: any): any;
        function data(p0: any, p1: any): any;
        function datalist(p0: any, p1: any): any;
        function dd(p0: any, p1: any): any;
        function defs(p0: any, p1: any): any;
        function del(p0: any, p1: any): any;
        function details(p0: any, p1: any): any;
        function dfn(p0: any, p1: any): any;
        function dialog(p0: any, p1: any): any;
        function div(p0: any, p1: any): any;
        function dl(p0: any, p1: any): any;
        function dt(p0: any, p1: any): any;
        function ellipse(p0: any, p1: any): any;
        function em(p0: any, p1: any): any;
        function embed(p0: any, p1: any): any;
        function fieldset(p0: any, p1: any): any;
        function figcaption(p0: any, p1: any): any;
        function figure(p0: any, p1: any): any;
        function footer(p0: any, p1: any): any;
        function form(p0: any, p1: any): any;
        function g(p0: any, p1: any): any;
        function h1(p0: any, p1: any): any;
        function h2(p0: any, p1: any): any;
        function h3(p0: any, p1: any): any;
        function h4(p0: any, p1: any): any;
        function h5(p0: any, p1: any): any;
        function h6(p0: any, p1: any): any;
        function head(p0: any, p1: any): any;
        function header(p0: any, p1: any): any;
        function hgroup(p0: any, p1: any): any;
        function hr(p0: any, p1: any): any;
        function html(p0: any, p1: any): any;
        function i(p0: any, p1: any): any;
        function iframe(p0: any, p1: any): any;
        function image(p0: any, p1: any): any;
        function img(p0: any, p1: any): any;
        function input(p0: any, p1: any): any;
        function ins(p0: any, p1: any): any;
        function kbd(p0: any, p1: any): any;
        function keygen(p0: any, p1: any): any;
        function label(p0: any, p1: any): any;
        function legend(p0: any, p1: any): any;
        function li(p0: any, p1: any): any;
        function line(p0: any, p1: any): any;
        function linearGradient(p0: any, p1: any): any;
        function link(p0: any, p1: any): any;
        function main(p0: any, p1: any): any;
        function map(p0: any, p1: any): any;
        function mark(p0: any, p1: any): any;
        function mask(p0: any, p1: any): any;
        function menu(p0: any, p1: any): any;
        function menuitem(p0: any, p1: any): any;
        function meta(p0: any, p1: any): any;
        function meter(p0: any, p1: any): any;
        function nav(p0: any, p1: any): any;
        function noscript(p0: any, p1: any): any;
        function object(p0: any, p1: any): any;
        function ol(p0: any, p1: any): any;
        function optgroup(p0: any, p1: any): any;
        function option(p0: any, p1: any): any;
        function output(p0: any, p1: any): any;
        function p(p0: any, p1: any): any;
        function param(p0: any, p1: any): any;
        function path(p0: any, p1: any): any;
        function pattern(p0: any, p1: any): any;
        function picture(p0: any, p1: any): any;
        function polygon(p0: any, p1: any): any;
        function polyline(p0: any, p1: any): any;
        function pre(p0: any, p1: any): any;
        function progress(p0: any, p1: any): any;
        function q(p0: any, p1: any): any;
        function radialGradient(p0: any, p1: any): any;
        function rect(p0: any, p1: any): any;
        function rp(p0: any, p1: any): any;
        function rt(p0: any, p1: any): any;
        function ruby(p0: any, p1: any): any;
        function s(p0: any, p1: any): any;
        function samp(p0: any, p1: any): any;
        function script(p0: any, p1: any): any;
        function section(p0: any, p1: any): any;
        function select(p0: any, p1: any): any;
        function small(p0: any, p1: any): any;
        function source(p0: any, p1: any): any;
        function span(p0: any, p1: any): any;
        function stop(p0: any, p1: any): any;
        function strong(p0: any, p1: any): any;
        function style(p0: any, p1: any): any;
        function sub(p0: any, p1: any): any;
        function summary(p0: any, p1: any): any;
        function sup(p0: any, p1: any): any;
        function svg(p0: any, p1: any): any;
        function table(p0: any, p1: any): any;
        function tbody(p0: any, p1: any): any;
        function td(p0: any, p1: any): any;
        function text(p0: any, p1: any): any;
        function textarea(p0: any, p1: any): any;
        function tfoot(p0: any, p1: any): any;
        function th(p0: any, p1: any): any;
        function thead(p0: any, p1: any): any;
        function time(p0: any, p1: any): any;
        function title(p0: any, p1: any): any;
        function tr(p0: any, p1: any): any;
        function track(p0: any, p1: any): any;
        function tspan(p0: any, p1: any): any;
        function u(p0: any, p1: any): any;
        function ul(p0: any, p1: any): any;
        /* Unspeakable name 'var'
        function var(p0: any, p1: any): any;
        */
        function video(p0: any, p1: any): any;
        function wbr(p0: any, p1: any): any;
    }
    namespace PropTypes {
        function any(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function array(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function arrayOf(typeChecker: any): any;
        function bool(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function element(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function func(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function instanceOf(expectedClass: any): any;
        function node(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function number(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function object(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function objectOf(typeChecker: any): any;
        function oneOf(expectedValues: any): any;
        function oneOfType(arrayOfTypeCheckers: any): any;
        function shape(shapeTypes: any): any;
        function string(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function symbol(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
    }
}
